package xyz.winson.one.model.entity;

import lombok.Data;

import java.util.Date;

/**
 * @author Winson One
 * @date 2019年09月27日 19:10
 * 角色资源关系实体模型
 */
@Data
public class SysRoleResource {
    /**
     * 角色资源关系ID，自增主键
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_resource.role_resource_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Long roleResourceId;

    /**
     * 角色ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_resource.role_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Long roleId;

    /**
     * 资源ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_resource.resource_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Long resourceId;

    /**
     * 创建人ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_resource.create_user_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Long createUserId;

    /**
     * 创建时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_resource.create_time
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Date createTime;
}