package xyz.winson.one.model.entity;

import java.util.Date;

/**
 * @author Winson One
 * @date 2019年09月27日 19:10
 * 角色资源关系实体模型
 */
public class SysRoleResource {
    /**
     * 角色资源关系ID，自增主键
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_resource.role_resource_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Long roleResourceId;

    /**
     * 角色ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_resource.role_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Long roleId;

    /**
     * 资源ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_resource.resource_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Long resourceId;

    /**
     * 创建人ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_resource.create_user_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Long createUserId;

    /**
     * 创建时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_resource.create_time
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_resource.role_resource_id
     *
     * @return the value of t_role_resource.role_resource_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public Long getRoleResourceId() {
        return roleResourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_resource.role_resource_id
     *
     * @param roleResourceId the value for t_role_resource.role_resource_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setRoleResourceId(Long roleResourceId) {
        this.roleResourceId = roleResourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_resource.role_id
     *
     * @return the value of t_role_resource.role_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_resource.role_id
     *
     * @param roleId the value for t_role_resource.role_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_resource.resource_id
     *
     * @return the value of t_role_resource.resource_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public Long getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_resource.resource_id
     *
     * @param resourceId the value for t_role_resource.resource_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_resource.create_user_id
     *
     * @return the value of t_role_resource.create_user_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_resource.create_user_id
     *
     * @param createUserId the value for t_role_resource.create_user_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_resource.create_time
     *
     * @return the value of t_role_resource.create_time
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_resource.create_time
     *
     * @param createTime the value for t_role_resource.create_time
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}