package xyz.winson.one.model.entity;

import java.util.Date;

/**
 * @author Winson One
 * @date 2019年09月27日 19:10
 * 系统角色实体模型
 */
public class SysRole {
    /**
     * 角色ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role.role_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Long roleId;

    /**
     * 角色名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role.role_name
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private String roleName;

    /**
     * 角色备注信息
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role.remark
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private String remark;

    /**
     * 角色状态
     * 1：有效，0：禁用
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role.state
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Integer state;

    /**
     * 是否已删除
     * 1：是，0否
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role.is_delete
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Byte isDelete;

    /**
     * 创建人ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role.create_user_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Long createUserId;

    /**
     * 创建时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role.create_time
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Date createTime;

    /**
     * 修改人ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role.update_user_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Long updateUserId;

    /**
     * 修改时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role.update_time
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role.role_id
     *
     * @return the value of t_sys_role.role_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role.role_id
     *
     * @param roleId the value for t_sys_role.role_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role.role_name
     *
     * @return the value of t_sys_role.role_name
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role.role_name
     *
     * @param roleName the value for t_sys_role.role_name
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role.remark
     *
     * @return the value of t_sys_role.remark
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role.remark
     *
     * @param remark the value for t_sys_role.remark
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role.state
     *
     * @return the value of t_sys_role.state
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role.state
     *
     * @param state the value for t_sys_role.state
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role.is_delete
     *
     * @return the value of t_sys_role.is_delete
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role.is_delete
     *
     * @param isDelete the value for t_sys_role.is_delete
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role.create_user_id
     *
     * @return the value of t_sys_role.create_user_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role.create_user_id
     *
     * @param createUserId the value for t_sys_role.create_user_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role.create_time
     *
     * @return the value of t_sys_role.create_time
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role.create_time
     *
     * @param createTime the value for t_sys_role.create_time
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role.update_user_id
     *
     * @return the value of t_sys_role.update_user_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role.update_user_id
     *
     * @param updateUserId the value for t_sys_role.update_user_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role.update_time
     *
     * @return the value of t_sys_role.update_time
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role.update_time
     *
     * @param updateTime the value for t_sys_role.update_time
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}