package xyz.winson.one.model.entity;

import java.util.Date;

/**
 * @author Winson One
 * @date 2019年09月27日 19:10
 * 系统资源实体模型
 */
public class SysResource {
    /**
     * 资源ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_resource.resource_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Long resourceId;

    /**
     * 资源名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_resource.resource_name
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private String resourceName;

    /**
     * 资源类型
     * 1：目录，2：菜单，3：按钮
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_resource.resource_type
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Integer resourceType;

    /**
     * 上级资源ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_resource.parent_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Long parentId;

    /**
     * 所有上级资源ID，通过逗号分隔
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_resource.parent_ids
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private String parentIds;

    /**
     * 资源图标
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_resource.icon
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private String icon;

    /**
     * 访问路径
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_resource.path
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private String path;

    /**
     * 备注信息
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_resource.remark
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private String remark;

    /**
     * 资源状态
     * 1：有效，0：禁用
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_resource.state
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Integer state;

    /**
     * 是否已删除
     * 1：是，0否
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_resource.is_delete
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Byte isDelete;

    /**
     * 创建人ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_resource.create_user_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Long createUserId;

    /**
     * 创建时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_resource.create_time
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Date createTime;

    /**
     * 修改人ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_resource.update_user_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Long updateUserId;

    /**
     * 修改时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_resource.update_time
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_resource.resource_id
     *
     * @return the value of t_sys_resource.resource_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public Long getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_resource.resource_id
     *
     * @param resourceId the value for t_sys_resource.resource_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_resource.resource_name
     *
     * @return the value of t_sys_resource.resource_name
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_resource.resource_name
     *
     * @param resourceName the value for t_sys_resource.resource_name
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_resource.resource_type
     *
     * @return the value of t_sys_resource.resource_type
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public Integer getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_resource.resource_type
     *
     * @param resourceType the value for t_sys_resource.resource_type
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setResourceType(Integer resourceType) {
        this.resourceType = resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_resource.parent_id
     *
     * @return the value of t_sys_resource.parent_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_resource.parent_id
     *
     * @param parentId the value for t_sys_resource.parent_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_resource.parent_ids
     *
     * @return the value of t_sys_resource.parent_ids
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public String getParentIds() {
        return parentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_resource.parent_ids
     *
     * @param parentIds the value for t_sys_resource.parent_ids
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setParentIds(String parentIds) {
        this.parentIds = parentIds == null ? null : parentIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_resource.icon
     *
     * @return the value of t_sys_resource.icon
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_resource.icon
     *
     * @param icon the value for t_sys_resource.icon
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_resource.path
     *
     * @return the value of t_sys_resource.path
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_resource.path
     *
     * @param path the value for t_sys_resource.path
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_resource.remark
     *
     * @return the value of t_sys_resource.remark
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_resource.remark
     *
     * @param remark the value for t_sys_resource.remark
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_resource.state
     *
     * @return the value of t_sys_resource.state
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_resource.state
     *
     * @param state the value for t_sys_resource.state
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_resource.is_delete
     *
     * @return the value of t_sys_resource.is_delete
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_resource.is_delete
     *
     * @param isDelete the value for t_sys_resource.is_delete
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_resource.create_user_id
     *
     * @return the value of t_sys_resource.create_user_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_resource.create_user_id
     *
     * @param createUserId the value for t_sys_resource.create_user_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_resource.create_time
     *
     * @return the value of t_sys_resource.create_time
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_resource.create_time
     *
     * @param createTime the value for t_sys_resource.create_time
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_resource.update_user_id
     *
     * @return the value of t_sys_resource.update_user_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_resource.update_user_id
     *
     * @param updateUserId the value for t_sys_resource.update_user_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_resource.update_time
     *
     * @return the value of t_sys_resource.update_time
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_resource.update_time
     *
     * @param updateTime the value for t_sys_resource.update_time
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}