package xyz.winson.one.model.entity;

import lombok.Data;

import java.util.Date;

/**
 * @author Winson One
 * @date 2019年09月27日 19:10
 * 系统用户实体模型
 */
@Data
public class SysUser {
    /**
     * 用户ID，自增主键
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Long id;

    /**
     * 用户名，登录名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.username
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private String username;

    /**
     * 用户昵称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.nickname
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private String nickname;

    /**
     * 密码
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.password
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private String password;

    /**
     * 加密盐值
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.salt
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private String salt;

    /**
     * 手机号码
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.mobile
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private String mobile;

    /**
     * 电子邮箱
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.email
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private String email;

    /**
     * 用户状态
     * 1：有效，0：禁用
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.state
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Integer state;

    /**
     * 是否已删除
     * 1：是，0否
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.is_delete
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Boolean isDelete;

    /**
     * 创建人ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.create_user_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Long createUserId;

    /**
     * 创建时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.create_time
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Date createTime;

    /**
     * 修改人ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.update_user_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Long updateUserId;

    /**
     * 修改时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.update_time
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Date updateTime;
}