package xyz.winson.one.model.entity;

import lombok.Data;

import java.util.Date;

/**
 * @author Winson One
 * @date 2019年09月27日 19:10
 * 用户角色关系实体模型
 */
@Data
public class SysUserRole {
    /**
     * 用户角色关系ID，自增主键
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.user_role_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Long userRoleId;

    /**
     * 用户ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.user_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Long userId;

    /**
     * 角色ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.role_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Long roleId;

    /**
     * 创建人ID
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.create_user_id
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Long createUserId;

    /**
     * 创建时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.create_time
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    private Date createTime;
}