package xyz.winson.one.mapper;

import xyz.winson.one.model.entity.SysRoleResource;

public interface SysRoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    int deleteByPrimaryKey(Long roleResourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    int insert(SysRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    int insertSelective(SysRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    SysRoleResource selectByPrimaryKey(Long roleResourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    int updateByPrimaryKeySelective(SysRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    int updateByPrimaryKey(SysRoleResource record);
}