package xyz.winson.one.mapper;

import xyz.winson.one.model.entity.SysResource;

public interface SysResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_resource
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    int deleteByPrimaryKey(Long resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_resource
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    int insert(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_resource
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    int insertSelective(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_resource
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    SysResource selectByPrimaryKey(Long resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_resource
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    int updateByPrimaryKeySelective(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_resource
     *
     * @mbg.generated Fri Sep 27 13:31:36 CST 2019
     */
    int updateByPrimaryKey(SysResource record);
}