spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-shiro?characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root123

jwt:
  secret: 57d57e13d69646b196800ab97303ee77
  expire: 30 # 过期时间，单位分钟
  issuer: springboot-shiro-vue