spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-shiro?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root123